spring:

  application:
    name: wallet-service

  config:
    import: configserver:http://localhost:8888

  profiles:
    active: dev


resilience4j:

  ratelimiter:
    instances:
      walletRateLimiter:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 0

  retry:
    instances:
      identityRetry:
        maxAttempts: 2
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

  timelimiter:
    instances:
      identityTimeout:
        timeoutDuration: 2s
        cancelRunningFuture: true

  bulkhead:
    instances:
      identityBulkhead:
        maxConcurrentCalls: 20
        maxWaitDuration: 200ms

  circuitbreaker:
    instances:
      identityCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true





#old those are moved to config file github

#
#spring:
#
#  application:
#    name: wallet-service
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/walletdb
#    username: walletuser
#    password: walletpass
#
#
#  jpa:
#    hibernate:
#      ddl-auto: validate
#
#    properties:
#      hibernate:
#        format_sql: true
#
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#
#management:
#
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#
#logging:
#  level:
#    org.hibernate.SQL: debug
#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#
#identity-service:
#  base-url: localhost://8081/api/v1
#
#
##eureka configuration
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${random.uuid}